name: "Music Assistant Alexa API Bridge"
version: "latest"
slug: "ma_alexa_api"
description: "Alexa API Bridge for Music Assistant (pulls prebuilt image)"
arch:
  - aarch64
  - amd64
startup: application
boot: manual         
image: "ghcr.io/alams154/music-assistant-alexa-api"
ports:
  "3000/tcp": 3000
webui: "http://[HOST]:[PORT:3000]/"
environment:
  USERNAME: "muasconnect"        # ändere
  PASSWORD: "SehrStark!"   # ändere
panel_icon: "mdi:amazon-alexa"
panel_title: "Alexa API"
